variable "project_id" {}
variable "network_name" {}
variable "routing_mode" {}
variable "subnet_01_name" {}
variable "subnet_01_ip" {}
variable "subnet_01_region" {}
variable "subnet_01_description" {}
variable "subnet_02_name" {}
variable "subnet_02_ip" {}
variable "subnet_02_region" {}
variable "subnet_02_description" {}
variable "subnet_01_secondary_svc_1_name" {}
variable "subnet_01_secondary_svc_1_range" {}
variable "subnet_01_secondary_svc_2_name" {}
variable "subnet_01_secondary_svc_2_range" {}
variable "subnet_01_secondary_pod_name" {}
variable "subnet_01_secondary_pod_range" {}
variable "subnet_02_secondary_svc_1_name" {}
variable "subnet_02_secondary_svc_1_range" {}
variable "subnet_02_secondary_svc_2_name" {}
variable "subnet_02_secondary_svc_2_range" {}
variable "subnet_02_secondary_pod_name" {}
variable "subnet_02_secondary_pod_range" {}
